"""add thumbnail_filename

Revision ID: 909cb80d0c9d
Revises: 94319ab531f4
Create Date: 2026-07-31 21:09:25.087682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909cb80d0c9d'
down_revision: Union[str, None] = '94319ab531f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_visuals', sa.Column('thumbnail_filename', sa.String(), nullable=True))
    op.add_column('visual_metadata', sa.Column('visual_type', sa.String(), nullable=True))
    op.add_column('visual_metadata', sa.Column('contains_handwriting', sa.Boolean(), nullable=True))
    op.add_column('visual_metadata', sa.Column('contains_diagram', sa.Boolean(), nullable=True))
    op.add_column('visual_metadata', sa.Column('contains_flowchart', sa.Boolean(), nullable=True))
    op.add_column('visual_metadata', sa.Column('contains_code', sa.Boolean(), nullable=True))
    op.add_column('visual_metadata', sa.Column('contains_equation', sa.Boolean(), nullable=True))
    op.add_column('visual_metadata', sa.Column('contains_table', sa.Boolean(), nullable=True))
    op.add_column('visual_metadata', sa.Column('detection_confidence', sa.Float(), nullable=True))
    op.drop_column('visual_metadata', 'has_math')
    op.drop_column('visual_metadata', 'has_handwriting')
    op.drop_column('visual_metadata', 'diagram_type')
    op.drop_column('visual_metadata', 'has_tables')
    op.drop_column('visual_metadata', 'content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visual_metadata', sa.Column('content_type', sa.VARCHAR(), nullable=True))
    op.add_column('visual_metadata', sa.Column('has_tables', sa.BOOLEAN(), nullable=True))
    op.add_column('visual_metadata', sa.Column('diagram_type', sa.VARCHAR(), nullable=True))
    op.add_column('visual_metadata', sa.Column('has_handwriting', sa.BOOLEAN(), nullable=True))
    op.add_column('visual_metadata', sa.Column('has_math', sa.BOOLEAN(), nullable=True))
    op.drop_column('visual_metadata', 'detection_confidence')
    op.drop_column('visual_metadata', 'contains_table')
    op.drop_column('visual_metadata', 'contains_equation')
    op.drop_column('visual_metadata', 'contains_code')
    op.drop_column('visual_metadata', 'contains_flowchart')
    op.drop_column('visual_metadata', 'contains_diagram')
    op.drop_column('visual_metadata', 'contains_handwriting')
    op.drop_column('visual_metadata', 'visual_type')
    op.drop_column('video_visuals', 'thumbnail_filename')
    # ### end Alembic commands ###
