"""Initial visuals tables

Revision ID: 94319ab531f4
Revises: 
Create Date: 2026-07-30 15:18:43.319268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94319ab531f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_visuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('timestamp_str', sa.String(), nullable=False),
    sa.Column('timestamp_sec', sa.Float(), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_visuals_id'), 'video_visuals', ['id'], unique=False)
    op.create_index(op.f('ix_video_visuals_video_id'), 'video_visuals', ['video_id'], unique=False)
    op.create_table('visual_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visual_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('diagram_type', sa.String(), nullable=True),
    sa.Column('has_math', sa.Boolean(), nullable=True),
    sa.Column('has_handwriting', sa.Boolean(), nullable=True),
    sa.Column('has_tables', sa.Boolean(), nullable=True),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['visual_id'], ['video_visuals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visual_id')
    )
    op.create_index(op.f('ix_visual_metadata_id'), 'visual_metadata', ['id'], unique=False)
    op.create_table('visual_ocrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visual_id', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['visual_id'], ['video_visuals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visual_id')
    )
    op.create_index(op.f('ix_visual_ocrs_id'), 'visual_ocrs', ['id'], unique=False)
    op.create_table('visual_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visual_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('timeline_event_name', sa.String(), nullable=False),
    sa.Column('transcript_segment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['visual_id'], ['video_visuals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visual_id')
    )
    op.create_index(op.f('ix_visual_timeline_id'), 'visual_timeline', ['id'], unique=False)
    op.create_index(op.f('ix_visual_timeline_video_id'), 'visual_timeline', ['video_id'], unique=False)
    op.create_table('visual_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visual_id', sa.Integer(), nullable=True),
    sa.Column('primary_topic', sa.String(), nullable=True),
    sa.Column('secondary_topic', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['visual_id'], ['video_visuals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visual_id')
    )
    op.create_index(op.f('ix_visual_topics_id'), 'visual_topics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visual_topics_id'), table_name='visual_topics')
    op.drop_table('visual_topics')
    op.drop_index(op.f('ix_visual_timeline_video_id'), table_name='visual_timeline')
    op.drop_index(op.f('ix_visual_timeline_id'), table_name='visual_timeline')
    op.drop_table('visual_timeline')
    op.drop_index(op.f('ix_visual_ocrs_id'), table_name='visual_ocrs')
    op.drop_table('visual_ocrs')
    op.drop_index(op.f('ix_visual_metadata_id'), table_name='visual_metadata')
    op.drop_table('visual_metadata')
    op.drop_index(op.f('ix_video_visuals_video_id'), table_name='video_visuals')
    op.drop_index(op.f('ix_video_visuals_id'), table_name='video_visuals')
    op.drop_table('video_visuals')
    # ### end Alembic commands ###
