'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { 
  Users, 
  Search, 
  FileText, 
  FolderOpen,
  PlayCircle,
  ArrowRight
} from 'lucide-react';
import { useAuth } from '@/lib/auth-context';
import { getUserSessions, CandidateEvaluationSession } from '@/lib/session-store';

export default function CandidatesPage() {
  const { user } = useAuth();
  const [sessions, setSessions] = useState<CandidateEvaluationSession[]>([]);
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    if (user?.email) {
      const userSessions = getUserSessions(user.email);
      setSessions(userSessions);
    }
  }, [user]);

  const filteredSessions = sessions.filter((s) => {
    const q = searchQuery.toLowerCase();
    return (
      s.candidateName.toLowerCase().includes(q) ||
      s.department.toLowerCase().includes(q) ||
      s.appliedRank.toLowerCase().includes(q)
    );
  });

  return (
    <div className="space-y-8 max-w-7xl">
      {/* Top Banner */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 p-6 rounded-2xl bg-gradient-to-r from-sky-950/80 via-slate-900 to-slate-950 border border-sky-500/20 shadow-xl backdrop-blur-xl">
        <div className="space-y-1">
          <div className="inline-flex items-center space-x-2 px-2.5 py-0.5 rounded-full bg-sky-500/10 border border-sky-500/30 text-sky-400 text-xs font-semibold">
            <Users className="h-3.5 w-3.5" />
            <span>Faculty Candidate Dossiers</span>
          </div>
          <h1 className="text-2xl font-bold text-white tracking-tight">Applicant Management & Dossier Reports</h1>
          <p className="text-xs text-slate-400">
            Recorded evaluation session reports generated by your account.
          </p>
        </div>

        <Link href="/dashboard/evaluation-session">
          <Button className="bg-sky-600 hover:bg-sky-500 text-white text-xs px-4 py-2 flex items-center space-x-1.5">
            <PlayCircle className="h-4 w-4" />
            <span>Start New Session</span>
          </Button>
        </Link>
      </div>

      {/* Search Bar */}
      {sessions.length > 0 && (
        <Card className="border-slate-800 bg-slate-900/60 backdrop-blur-md p-4">
          <div className="relative w-full sm:w-80">
            <Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-500" />
            <input
              type="text"
              placeholder="Search dossier file or department..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-lg pl-9 pr-3 py-2 text-xs text-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-sky-500"
            />
          </div>
        </Card>
      )}

      {/* Candidate Reports List */}
      {sessions.length === 0 ? (
        <Card className="border-slate-800 bg-slate-900/40 border-dashed backdrop-blur-md p-12 text-center flex flex-col items-center justify-center min-h-[300px] space-y-4">
          <div className="h-12 w-12 rounded-2xl bg-slate-800/80 border border-slate-700 flex items-center justify-center text-slate-500">
            <FolderOpen className="h-6 w-6" />
          </div>
          <div className="space-y-1">
            <h3 className="text-sm font-semibold text-white">No Candidate Evaluation Dossiers Found</h3>
            <p className="text-xs text-slate-400 max-w-sm">
              You currently have no recorded evaluation sessions. Start an interview session to generate reports.
            </p>
          </div>
          <Link href="/dashboard/evaluation-session">
            <Button className="bg-sky-600 hover:bg-sky-500 text-white text-xs px-4 py-2 mt-2">
              Start Evaluation Session
            </Button>
          </Link>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {filteredSessions.map((cand) => (
            <Card key={cand.id} className="border-slate-800 bg-slate-900/60 hover:border-slate-700 transition-all backdrop-blur-md p-6 space-y-4">
              <div className="flex items-start justify-between">
                <div className="flex items-center space-x-3">
                  <div className="h-11 w-11 rounded-full bg-gradient-to-tr from-sky-600 to-indigo-600 flex items-center justify-center font-bold text-xs text-white shadow-md">
                    <FileText className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="text-base font-bold text-white truncate max-w-[200px]">{cand.candidateName}</h3>
                    <p className="text-xs text-slate-400">{cand.department}</p>
                    <p className="text-[11px] text-sky-400 font-medium">{cand.appliedRank}</p>
                  </div>
                </div>

                <div className="text-right">
                  <span className="text-[10px] text-slate-400 uppercase block font-medium">Consensus</span>
                  <span className="text-2xl font-extrabold text-emerald-400 font-mono">{cand.scores.overallScore}%</span>
                </div>
              </div>

              {/* Agent Scores Breakdown */}
              <div className="grid grid-cols-4 gap-2 pt-2 border-t border-slate-800/80 text-center">
                <div className="p-2 rounded-lg bg-slate-950/60 border border-slate-800">
                  <span className="text-[9px] text-slate-400 block font-medium">Resume</span>
                  <span className="text-xs font-bold text-sky-400 font-mono">{cand.scores.resumeScore}%</span>
                </div>
                <div className="p-2 rounded-lg bg-slate-950/60 border border-slate-800">
                  <span className="text-[9px] text-slate-400 block font-medium">Video</span>
                  <span className="text-xs font-bold text-indigo-400 font-mono">{cand.scores.videoScore}%</span>
                </div>
                <div className="p-2 rounded-lg bg-slate-950/60 border border-slate-800">
                  <span className="text-[9px] text-slate-400 block font-medium">Coding</span>
                  <span className="text-xs font-bold text-emerald-400 font-mono">{cand.scores.codingScore}%</span>
                </div>
                <div className="p-2 rounded-lg bg-slate-950/60 border border-slate-800">
                  <span className="text-[9px] text-slate-400 block font-medium">Q&A</span>
                  <span className="text-xs font-bold text-amber-400 font-mono">{cand.scores.interactionScore}%</span>
                </div>
              </div>

              <div className="flex items-center justify-between pt-2">
                <span className="px-2.5 py-1 rounded-full text-[10px] font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                  {cand.recommendation}
                </span>

                <Link href="/dashboard/evaluation-session">
                  <Button className="bg-sky-600 hover:bg-sky-500 text-white text-xs px-3 py-1.5 flex items-center space-x-1">
                    <span>View Session Workflow</span>
                    <ArrowRight className="h-3.5 w-3.5" />
                  </Button>
                </Link>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
