apiVersion: v1
kind: Secret
metadata:
  name: facultyiq-secrets
  namespace: facultyiq-prod
type: Opaque
stringData:
  SECRET_KEY: "prod_secret_key_change_in_real_vault_32chars"
  POSTGRES_PASSWORD: "facultyiq_secure_password_123"
  REDIS_PASSWORD: "redis_secure_password_123"
